---
#Have fun with Mysql!

- name: Include variables
  include_vars: mysql.yml

- name: Start the MySQL service
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ sqlstart }}"

- name: create database for comanage
  mysql_db:
    name: registry
    state: present

- name: create user for mysql with all privilege
  mysql_user:
    name: comanage
    password: C0man4ge
    priv: registry.*:ALL
    state: present

#- name: copy .my.cnf file with root password credentials
#  template:
#    src: my.cnf.j2
#    dest: /etc/mysql/my.cnf
#    owner: root
#    mode: 0600

- name: Restart the MySQL service
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ sqlrestart }}"
